// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:spelly/data/grammer/hive/grammer_history.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(GrammerHistoryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(GrammerHistoryAdapter());
  }
}
